version: '3.7'

services:
  yarn:
    image: node:16.13.2
    networks:
      - net_api_treinamento
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "4173:4173"
    working_dir: /app
    volumes:
      - ./app/:/app/
    entrypoint: yarn

networks:
  net_api_treinamento:
    external: true
