export const CodeErrorMessage = {
  TIMEOUT: 'Tempo Excedido',
  UNKNOWN_ERROR: 'Erro Desconhecimento',
  UNAUTHORIZED: 'Não Autorizado',
  ACCESS_DENIED: 'Acesso Negado',
  INTERNAL_SERVER_ERROR: 'Erro interno no servidor',
  NETWORK_ERROR: 'Erro de comunicação, certifique-se sua conexão com a internet',
  FAILED_FIRST_ACCESS: 'Falha ao realizar o primeiro acesso',
  FAILED_CHANGE_PASSWORD: 'Falha ao alterar senha',
  FAILED_REQUEST_CHANGE_PASSWORD: 'Falha ao solicitar recuperação de senha',
  FAILED_LOAD_DASHBOARD: 'Falha ao carregar dashboard',
  FAILED_LOAD_PROFILE: 'Falha ao carregar perfil',
  FAILED_LOAD_USER: 'Falha ao carregar usuário',
  FAILED_CHANGE_USER: 'Falha ao alterar usuário',
  FAILED_CREATE_USER: 'Falha ao criar usuário',
  FAILED_ENABLE_USER: 'Falha ao ativar usuário',
  FAILED_DISABLE_USER: 'Falha ao desativar usuário',
  FAILED_REMOVE_USER: 'Falha ao remover usuário',
};
